name: nighteye_lite
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cpuonly
  - pip
  - pip:
      - opencv-python-headless
      - ultralytics
      - requests